
import = [
	"~/.config/alacritty/catpuccin_mocha.toml"
]

shell = "tmux"
live_config_reload = true

[window]
dynamic_title = true
dimensions = { columns = 130, lines = 28 }
decorations = "Full"

opacity = 0
blur =  false

resize_increments = true

[scrolling]
history = 0 # Handled by tmux

[font]
normal = { family = 		"Ubuntu Mono", style = "Regular"}
bold = { family = 			"Ubuntu Mono", style = "Bold"}
italic = { family = 		"Ubuntu Mono", style = "Regular Italic"}
bold_italic = { family = 	"Ubuntu Mono", style = "Bold Italic"}
size = 9.5625

[cursor]
style = { shape = "Beam", blinking = "Off" }
blink_interval = 500
thickness = 0.1

[mouse]
bindings = [
	{ mouse = "Right", mods = "None", action = "Copy" },
]

[[keyboard.bindings]]
key = "Alt"
mods = "Control"
chars = "\uE000"
