import = [
	"~/.config/alacritty/theme"
]

shell = "tmux"
live_config_reload = true

[window]
dimensions = { columns = 120, lines = 28 }
decorations = "Full"

opacity = 0.86
blur =  true

resize_increments = true

[scrolling]
history = 0 # Handled by tmux

[font]
size = 9

[cursor]
style = { shape = "Beam", blinking = "Off" }
blink_interval = 500
thickness = 0.1

[mouse]
bindings = [
	{ mouse = "Right", mods = "None", action = "Copy" },
]

[[keyboard.bindings]]
key = "Alt"
mods = "Control"
chars = "\uE000"
